sudo: false
language: python
before_install:
- openssl aes-256-cbc -K $encrypted_863770fa82d5_key -iv $encrypted_863770fa82d5_iv
  -in aweforms-gae-service-key.json.enc -out aweforms-gae-service-key.json -d
- mkdir -p lib
install:
- pip install -r requirements.txt -t lib/
script:
- echo "No Script to run"
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: aweforms-gae-service-key.json
  project: awe-forms
  default: true
  on:
    all_branches: deployment-gae
